#### THIS IS A TEMPLATE ####
# This workflow is created to be a template for every time an e2e test is required,

on:
  workflow_call:
    inputs:
      k8s-version:
        required: true
        type: string
      variation:
        type: string

permissions:
  contents: read

jobs:
  kubernetes:
    name: Kubernetes ${{ inputs.variation }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Load images from cache
        run: |
          mkdir -p test/junitreports
          echo "loading docker images..." >test/junitreports/report-121.xml

      - name: Upload e2e junit-reports ${{ inputs.variation }}
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: success() || failure()
        with:
          name: e2e-test-reports-${{ inputs.k8s-version }}${{ inputs.variation }}
          path: 'test/junitreports/report*.xml'

